# Usa una imagen de Node.js para compilar
FROM node:18 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto
COPY package.json package-lock.json ./
RUN npm install

# Copiar el resto del código y construir la app
COPY . .
RUN npm run build

# Servir la aplicación con Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Exponer el puerto
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
